### ISSUE TITLE
Edit a Category (8)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#31]
As an admin I would like to be able to modify a Category so that I can rephrase the name if I think of something more appropriate.

**Given** the user is viewing the Category list  
**When** they select the option to edit an Category  
**Then** the user should be directed to a form and given the ability to change the Category's name  

**Given** the user is finished updating the Category information  
**When** they click the `Save` button  
**Then** the updated Category should be saved to the database  
**And** the user should be redirected to the new Category List page  

**Given** the user has decided not to edit the Category  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

**Comment by mandapandaa8** [comment]
client

- in categorylist.js, create/refactor an edit button on each post. This will navigate to categories/edit/${categoryId}.
- copy "new category" form, to make an "edit" form,
- render edit form with existing category information using defaultvalue and currentcategory transient state.
- track state changes in the input fields, and update currentCategory state.
- When user clicks save, copy currentCategory state to variable "category" and then invoke function "updateCategory" with parameter of "category" .
- updateCategory() should send a POST request to the API through the cagtegorymanager file.
- Navigate to /categories/${categoryId})

**Comment by mandapandaa8** [comment]
SERVER SIDE

- 
- Create an update function in the CategoryView class from the file categories_views
- Update function should include a PUT request
- Use .get() to retrieve the single object being edited ( ___.objects.get(pk=pk) )
- Use request.data to retrieve data from client side
- use .save() at the bottom of the function to update the changes
- Add return Response(None, status=status.HTTP_204_NO_CONTENT) as the last line

**Comment by MckenzieLR** [comment]
Change key names on object that we are getting back from server side to match server side casing (snake case) and remove "id" if included on any keys since django adds it for us
