### ISSUE TITLE
Edit a Post (8)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#33]
As a author I would like to be able to modify my Posts so that I can correct mistakes or add additional content.

**Given** the user is viewing the Post list  
**When** they select the option to edit an Post  
**Then** the user should be directed to a form and given the ability to change the Post's information  

**Given** the user is finished updating the Post information  
**When** they click the `Save` button  
**Then** the updated Post should be saved to the database  
**And** the user should be redirected to the new Post's details page

**Given** the user has decided not to edit the Post  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

Editable Information

* Title
* Content
* Category
* Header Image URL (optional)

**Comment by Russ716** [comment]
client - in postlist.js, edit button on each post. navigate to posts/edit/${postId}. copy new post form, and render with existing post information using defaultvalue and currentpost transient state. 
track state changes in the input fields, and update currentPost state. When user clicks save, copy currentPost state to variable "post" and then invoke function "updatePost" with parameter of "post" . updatePost() should send a POST request to the API through the postmanager file. 
Navigate to /posts/${postId})

**Comment by ameena-mashaikh** [comment]
**SERVER SIDE**

- Create an update function in the PostView class from the file posts_views
- Update function should include a PUT request
- Use .get() to retrieve the single object being edited ( ___.objects.get(pk=pk) )
- Use request.data to retrieve data from client side
- use .save() at the bottom of the function to update the changes
- Add return Response(None, status=status.HTTP_204_NO_CONTENT) as the last line

**Comment by MckenzieLR** [comment]
Change key names on object that we are getting back from server side to match server side casing (snake case) and remove "id" if included on any keys since django adds it for us
