### ISSUE TITLE
Create a Post (5)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#39]
As an author, I would like to be able to create Posts so I can share my thoughts with the world.

**Given** a user is in the app  
**When** they select the `New Post` menu option
**Then** they should be directed to a page with a form for creating a new post

**Given** the user has entered the relevant information for a Post
**When** they click the `Save` button  
**Then** the Post should be saved to the database  
**And** the creation datetime should be automatically set to the current date and time  
**And** the post should automatically be approved  
**And** the user should be recorded as the author of the Post  
**And** the user should be redirected to the new Post's details page

The "relevant information" for a Post is

* Title
* Content
* Category
* Publication date (current date)
* Header Image URL (optional)

**Comment by Russ716** [comment]
create model and views for a post. use client variable names on the server. 
    Title    Content    Category    Publication date (current date)    Header Image URL (optional)
build form for create the post clientside with save button. 
save in database on serverside. user is recorded as author. (Capture logged in user token) navigate to `http://localhost:8088/posts/${postId}`)

**Comment by Russ716** [comment]
create post.py in models folder. Needs "relevant information" above, and to match the client side variable name structure. 
create posts_view.py in views folder. Post view will need defs for create/update/retrieve/list/destroy
post serializer with meta having model information

clientside - build post manager.js in managers folder that is responsible for holding all fetch functions (get/post/delete/put)
make "new post" button on postlist.js, navigate to posts/new/${postId}
build form there that will be saved with the "create" def in the view. Capture user token as author. capture current date/time and attach to post. Navigate to /posts/${postId})
create corresponding route in application views. link postId with useParams  in the postlist.js
