### ISSUE TITLE
Create a Category (5)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#42]
As an author I would like to be able to create a new category so that I can better classify my posts.

**Given** an author is on the Category list page  
**When** they select the `Create Category` button  
**Then** they should be directed to a form in which they can enter a new category name  

**Given** an author has entered a Category name  
**When** they click the `Save` button  
**Then** a new category should be saved to the database  
**And** the author should be directed to the Category list page

**Comment by mandapandaa8** [comment]
create model and views for a category. use client variable names on the server.
category name
build form for create the category clientside with save button.
save in database on serverside.

**Comment by mandapandaa8** [comment]
create category.py in models folder. Needs "relevant information" above, and to match the client side variable name structure.
create categories_view.py in views folder. Post view will need defs for create/update/retrieve/list/destroy
post serializer with meta having model information

clientside - build category manager.js in managers folder that is responsible for holding all fetch functions (get/post/delete/put)
make "new category" button in categorylist.js, navigate to categories/new/${categoryId}
build form there that will be saved with the "create" def in the view. Navigate to /categories/${categoryId})
create corresponding route in application views. link postId with useParams in the categorylist.js
